import DashboardMedici from "@/components/DashboardMedici";
import Head from "next/head";
import Link from "next/link";
import { useEffect } from "react";
import { useAuth } from "../context/AuthContext";

export default function Home() {
  const { currentUser } = useAuth();
  useEffect(() => {
    console.log(currentUser);
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {currentUser ? (
        <>
          <h1>JONULE TE-AI LOGAT</h1>
        </>
      ) : (
        <div className="text-center flex flex-col">
          <h1 className="text-2xl mt-10">
            Scapa de cozile interminabile de la medicul de familie.
          </h1>
          <h2 className="text-2xl mt-10">Fa ti cont pentru a incepe</h2>
        </div>
      )}
    </>
  );
}
