import DashboardMedici from "@/components/DashboardMedici";
import Head from "next/head";
import { useEffect } from "react";
import { useAuth } from "../context/AuthContext";

export default function Home() {
  const { currentUser } = useAuth();
  useEffect(() => {
    console.log(currentUser);
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardMedici />
    </>
  );
}
